import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowDownRight,ArrowUpRight,Mail,Menu,X,ExternalLink} from 'lucide-react';
import {FaGithub,FaLinkedin,FaInstagram,FaWhatsapp,FaFacebook,FaTwitter} from 'react-icons/fa6';
import ContactSection from './components/contact.jsx';
import './styles.css';

const SOCIAL_LINKS=[
 {key:'github',label:'GitHub',Icon:FaGithub,href:'https://github.com/ahmad012-ui'},
 {key:'linkedin',label:'LinkedIn',Icon:FaLinkedin,href:'https://www.linkedin.com/in/ahmad-rehman-29b268316/'},
 {key:'instagram',label:'Instagram',Icon:FaInstagram,href:'https://www.instagram.com/ahmad.rehmn/'},
 {key:'whatsapp',label:'WhatsApp',Icon:FaWhatsapp,href:'https://wa.me/923112607492'},
 {key:'email',label:'Email',Icon:Mail,href:'mailto:codeby.ahmad@gmail.com'},
 {key:'facebook',label:'Facebook',Icon:FaFacebook,href:'https://www.facebook.com/profile.php?id=61581994023105'},
 {key:'x',label:'X / Twitter',Icon:FaTwitter,href:'https://x.com/ahmad_rehmn?t=RF2IG7vyyWwW9rclYRX2Jhg&s=09'}
];
const MAIN_SOCIAL=['github','linkedin','facebook','x','instagram','whatsapp','email'];
function SocialIcons(){return SOCIAL_LINKS.filter(s=>MAIN_SOCIAL.includes(s.key)).map(s=>{const Icon=s.Icon;return <a key={s.key} className="social-icon" href={s.href} aria-label={s.label} title={s.label} target={s.key==='email'?undefined:'_blank'} rel={s.key==='email'?undefined:'noreferrer'}><Icon/></a>})}
const projects=[
 {n:'01',title:'Vaccino',type:'Vaccination Management System',desc:'A full-stack vaccination management system for managing hospitals, vaccines, appointments and patient workflows with a structured PHP and MySQL backend.',stack:['PHP','MySQL','JavaScript'],repo:'https://github.com/ahmad012-ui/vaccination-management-system',image:'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80'},
 {n:'02',title:'MTCC Admin Portal',type:'Admin Dashboard',desc:'A responsive React admin dashboard with reusable UI components, structured workflows and Tailwind CSS layouts designed for efficient data and platform management.',stack:['React','Vite','Tailwind CSS'],repo:'https://github.com/ahmad012-ui/MTCC-Admin-Portal',image:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80'},
 {n:'03',title:'Baadshah Tools',type:'E-commerce / Catalog',desc:'A responsive WordPress product catalogue built with Elementor, focused on clear product presentation, intuitive browsing and a clean, conversion-focused interface.',stack:['WordPress','Elementor','CSS'],repo:'',image:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80'},
 {n:'04',title:'Furniro',type:'Furniture Landing Page',desc:'A responsive furniture ecommerce landing page recreated from a design with careful attention to layout, spacing, visual hierarchy and responsive behavior.',stack:['HTML','CSS','JavaScript'],repo:'https://github.com/ahmad012-ui/Furniro-Furniture-Landing-Page',image:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'}
];
const skills={Frontend:['HTML','CSS','JavaScript','React','Tailwind CSS','Bootstrap','jQuery'],Backend:['PHP','ASP.NET MVC','REST APIs'],Database:['MySQL','SQL Server'],Tools:['Git','GitHub','Figma','VS Code','Visual Studio'],Testing:['Manual Testing','Bug Reporting','Regression Testing','API Testing','UI Testing']};
function App(){
 const [menu,setMenu]=useState(false),[active,setActive]=useState('home');
 useEffect(()=>{const els=[...document.querySelectorAll('section[id]')];const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-35% 0px -55%'});els.forEach(e=>obs.observe(e));return()=>obs.disconnect()},[]);
 const nav=['about','skills','projects','experience','contact'];
 return <div className="site">
  <header className="nav"><a className="brand" href="#home" onClick={()=>setMenu(false)}><span>AR</span><b>AHMAD REHMAN</b></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}><a className={active==='home'?'active':''} href="#home" onClick={()=>setMenu(false)}>HOME</a>{nav.map(x=><a key={x} className={active===x?'active':''} href={'#'+x} onClick={()=>setMenu(false)}>{x.toUpperCase()}</a>)}</nav></header>
  <aside className="index"><a href="#home">01<span>HOME</span></a><a href="#about">02<span>ABOUT</span></a><a href="#skills">03<span>SKILLS</span></a><a href="#projects">04<span>PROJECTS</span></a><a href="#experience">05<span>EXPERIENCE</span></a><a href="#contact">06<span>CONTACT</span></a></aside>
  <main>
   <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">FRONTEND DEVELOPER / QA ENGINEER</p><h1>I BUILD WEB<br/>EXPERIENCES<br/>THAT <em>WORK.</em></h1><p className="lead">Responsive interfaces, clean implementation and a QA mindset. I build products that look right, behave right and feel right.</p><div className="actions"><a className="btn solid" href="#projects">VIEW MY WORK <ArrowUpRight/></a><a className="btn" href="#contact">LET'S CONNECT <ArrowUpRight/></a></div><div className="social"><span className="social-label">FIND ME ON</span><SocialIcons/></div></div><div className="hero-art" aria-hidden="true"><div className="orb orb1"/><div className="orb orb2"/><div className="cross">+</div><div className="availability"><i/> <b>AVAILABLE FOR OPPORTUNITIES</b><p>Open to interesting projects and frontend roles.</p></div></div></section>
   <section id="about" className="section about"><div className="section-label">02<br/><span>ABOUT</span></div><div className="section-inner two"><div><p className="eyebrow">GET TO KNOW ME</p><h2>A LITTLE<br/>ABOUT <em>ME.</em></h2><p>I'm Ahmad Rehman, a frontend developer with a growing QA engineering background. I enjoy turning designs and ideas into responsive web interfaces, then testing them until the details hold up.</p><p>I'm Ahmad Rehman, a frontend developer with a growing QA engineering background. I enjoy turning designs and ideas into responsive web interfaces, then testing them until the details hold up.</p><a className="text-link" href="#contact">LET'S TALK <ArrowUpRight/></a></div><div className="details"><div><span>ROLE</span><b>Frontend Developer / QA</b></div><div><span>FOCUS</span><b>Web UI · Testing · UX</b></div><div><span>STACK</span><b>React · JavaScript · CSS</b></div><div><span>BASED</span><b>Pakistan</b></div></div></div></section>
   <section id="skills" className="section skills"><div className="section-label">03<br/><span>SKILLS</span></div><div className="section-inner"><p className="eyebrow">WHAT I USE</p><h2>THINGS I BUILD<br/>WITH.</h2><div className="skill-grid">{Object.entries(skills).map(([cat,items])=><div className="skill-col" key={cat}><h3>{cat}</h3>{items.map(s=><span key={s}>{s}</span>)}</div>)}</div></div></section>
   <section id="projects" className="section projects"><div className="section-label">04<br/><span>PROJECTS</span></div><div className="section-inner"><div className="project-heading"><div><p className="eyebrow">SELECTED WORK</p><h2>PROJECTS THAT<br/>SOLVE <em>REAL PROBLEMS.</em></h2></div><a className="text-link" href="https://github.com/ahmad012-ui" target="_blank" rel="noreferrer">VIEW GITHUB <ExternalLink/></a></div><div className="project-list">{projects.map(p=><article className="project" key={p.n}><div className="project-no">{p.n}</div><div className="project-preview"><img src={p.image} alt={p.title}/><div className="preview-lines"><i/><i/><i/><i/></div><span>{p.title.toUpperCase()}</span></div><div className="project-info"><p>{p.type}</p><h3>{p.title}</h3><p className="desc">{p.desc}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div><div className="project-link">{p.repo?<a href={p.repo} target="_blank" rel="noreferrer">GITHUB <ArrowUpRight/></a>:<span>CASE STUDY</span>}</div></article>)}</div></div></section>
   <section id="experience" className="section experience"><div className="section-label">05<br/><span>EXPERIENCE</span></div><div className="section-inner"><p className="eyebrow">MY JOURNEY</p><h2>EXPERIENCE<br/>THAT SHAPED <em>ME.</em></h2><div className="timeline"><div><b>2026 — PRESENT</b><h3>Frontend Developer / QA</h3><p>Building responsive interfaces, working with real-world applications and testing features for functional and UI issues.</p></div><div><b>2026</b><h3>UI/UX & Frontend Development</h3><p>Turning designs into responsive pages and reusable frontend components while improving implementation quality.</p></div><div><b>EARLIER</b><h3>Frontend Projects</h3><p>Built personal and academic projects across HTML, CSS, JavaScript, PHP, React and databases.</p></div></div></div></section>
   <section id="contact" className="section contact"><div className="section-label">06<br/><span>CONTACT</span></div><ContactSection/></section>
  </main>
  <footer><a className="brand" href="#home"><span>AR</span><b>AHMAD REHMAN</b></a><small>© 2026 AHMAD REHMAN. ALL RIGHTS RESERVED.</small><a className="back" href="#home">BACK TO TOP <ArrowDownRight/></a></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
